---
title: "TRIZ - 参考文档"
date: "2024-08-06"
date-modified: " `r Sys.Date()`"
order: 400
summary: "本模块是我在班加罗尔 Srishti Manipal Institute 教授的创造性问题解决课程的一部分"
categories: ""
# url_code: ""
# url_pdf: ""
# url_slides: "slides/PlayAndInvent/TRIZ-Basics/index.html"
# url_video: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 简介

这是我在 TRIZ 各个方面收集的文档的带注释和嵌入列表。所有文档都可下载,旨在推广 TRIZ 意识!

让我先在这里放上我的 TRIZ 演讲!!

{{< video https://www.youtube.com/watch?v=fwt4NcfefNE >}}

## 概述

1. Stan Kaplan. *TRIZ 入门*. <u>[PDF](TRIZ-related/Stan Kaplan-Intro-to-TRIZ.pdf)</u>. 如果你只能阅读一份 TRIZ 文档,那就请阅读这本小册子。

1. Lev Shulyak. *TRIZ 入门*. <u>[PDF](TRIZ-related/Shulyak-Intro-to-TRIZ.pdf)</u>. 简短的两页介绍。

1. Simon Litvin, Vladimir Petrov, Mikhail Rubin, Victor Fey. *TRIZ 知识体系*. <u>[PDF](TRIZ-related/TRIZ-Body-of-Knowledge-final.pdf)</u>. 一页 TRIZ 系统地图,附带丰富的参考文献。由 TRIZ 大师汇编。

1. *什么是 TRIZ?* 演示文稿。 <u>[PDF](TRIZ-related/Chapter 7 TRIZ.pdf)</u>

1. Yaroslav Baronov. *TRIZ 概述*. <u>[PDF](TRIZ-related/trizoverviewyaroslav-120912103927-phpapp01.pdf)</u>

1. Cal Halliburton, Victoria Roza.(2005年12月). *设计的新工具*. The Technology Teacher, 国际技术教育协会期刊。 <u>[PDF](TRIZ-related/NewToolsforDesign.pdf)</u>

1. Valeri Souchkov. (2006年11月,2011年11月更新). *TRIZ 关键组件和技术注释列表*. <u>[PDF](TRIZ-related/Annotated list of main TRIZ tools and techniques.pdf)</u>

1. Martin G. Moehrle.(2005) *什么是 TRIZ?从概念基础到研究框架*. 创造力与创新管理, 第14卷第1期, 2005年3月。 <u>[PDF](TRIZ-related/Moehrle2005.pdf)</u>

1. Khomenko N. *经典 TRIZ 和 OTSM 超简短介绍*. <u>[PDF](TRIZ-related/khomenko-supershortintroductionintoclassicaltrizandotsm.pdf)</u>

1. G.S. Altshuller, R.B. Shapiro (1956). *发明创造心理学*. TRIZ 评论: 国际 TRIZ 协会 – MATRIZ 期刊。 第1卷, #1, 2019年2月。 <u>[PDF](TRIZ-related/Psychology-1956-en.pdf)</u>

1. Felicito S. Caluyo. *创新与发明问题解决理论 (TRIZ): 演示*. <u>[PDF](TRIZ-relatedCahuyo - Innovation-and-the-Theory-of-Inventive-Problem-Solving-TRIZ.pdfu)</u>

### G. S. Altshuller 的著作

1. Altshuller G.S. <u>[*发明的艺术——突然出现的发明家*](https://library.lol/main/8EEDC7B5ABAC7A453CD79A71C0B12B59)</u>. 莫斯科: Detskaya Literatura, 1989 (第1版-1984; 第2版-1987; 第3版- 1989). ISBN 5-08-000598-X.

>这本书以通俗方式编写,面向青少年。读者可以在本书中学习78个真实的发明问题,并学习应用27种实用工具和技术来解决所提出的问题。书中包括为未来发明者提供的一些建议。

2. Altshuller, G.S. (1984). <u>[*创造力作为一门精确科学:发明问题解决理论*](https://library.lol/main/8E4F8A71C889CA30003D21D644195FCC)</u>. Gordon and Breach Science Publishers, 纽约。
> 本书包括70个发明问题的描述,ARIZ-77以及使用新版本 ARIZ 解决问题的几个示例。

> 本书提出了技术系统演化定律体系、发明规则(标准)的第一个版本以及物-场分析原理。

> 书中还包括40个发明原理及其演化的文章、系统 S 曲线生命周期的文章、科学问题解决方法的文章,以及使用几种物理效应进行发明问题解决的表格。

3. Altshuller, G.S. (1999) <u>[*创新算法: TRIZ、系统创新和技术创造力*](https://library.lol/main/71BF1D23C6AB2A5896E1B4441F628AFE)</u>. Technical Innovation Center, 伍斯特, 马萨诸塞州。

4. Altshuller, G.S. (1991) *寻找想法:发明问题解决理论入门*, 第2版。 Nauka, 新西伯利亚。

## TRIZ 示例

1. Arvind 的 TRIZ 案例研究数据库 `r emoji::emoji("laugh")`! <u>[在线演示](/slides/PlayAndInvent/TRIZ-Database/index.html)</u>

1. The TRIZ Journal. *发明原理示例* <u><https://the-trizjournal.com/40-inventive-principles-examples/></u>

1. 建筑学的40个发明原理。 <u>[PDF](TRIZ-rela40-Inventive-Principles-for-Architecture.pdf)</u>

1. 商业的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Business.pdf)</u>

1. 化学工程的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Chemical-Engineering.pdf)</u>

1. 建筑的40个发明原理。
<u>[PDF](TRIZ-related/40-Inventive-Principles-for-Construction.pdf)</u>

1. 客户满意的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Customer-Satisfaction.pdf)</u>

1. 客户满意的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Customer-Satisfaction.pdf)</u>

1. 教育的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Education.pdf)</u>

1. Stefano Filippia, Daniela Barattina. *在交互设计中利用 TRIZ 工具*. 世界会议: TRIZ FUTURE, TF 2011-2014。 <u>[PDF](TRIZ-related/TRIZ in Interaction design.pdf)</u>

1. 食品工业的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Food-Industry.pdf)</u>

1. 营销和销售的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Marketing-Sales-and-Advertising.pdf)</u>

1. Ismail Ekmekcia, Mustafa Koksala. (2015). *TRIZ 方法论及产品开发应用示例*. 技术、创新和企业家精神世界会议。 <u>[PDF](TRIZ-related/TRIZ for Product Design.pdf)</u>

1. 质量管理的40个发明原理。 <u>[PDF](TRIZ-related/40-Inventive-Principles-for-Quality-Management.pdf)</u>

1. Boris Zlotin, Alla Zusman, Len Kaplan, Svetlana Visnepolschi, Vladimir Proseanic 和 Sergey Malkin. *超越技术的 TRIZ:将 TRIZ 应用于非技术领域的理论与实践*. <u>[PDF](TRIZ-related/TRIZ Beyond Technology.pdf)</u>

1. Valeri Souchkov. *用 TRIZ 制作:成功的 TRIZ 案例*. <u>[PDF](TRIZ-related/Souchkov - Made With TRIZ - Successful TRIZ cases.pdf)</u>

1. GearWrench. *X-Beam 扳手产品表*.  <u>[PDF](TRIZ-related/GW_XL_X-Beam_Sellsheet.pdf)</u>. 使用 TRIZ 发明原理 IP "另一维度"。

1. Julian F.V. Vincent, Olga Bogatyreva, Anja-Karina Pahl, Nikolay Bogatyrev 和 Adrian Bowyer. *将生物学引入 TRIZ:生物效应数据库*. <u>[PDF](TRIZ-related/Biological-Effects-in-TRIZ.pdf)</u>


来自 TETRIS 项目

1. Project TETRIS. *防撞钥匙*. <u>[PDF](TRIZ-related/TRIZ-ExamplesEN/EN_ex_1.pdf)</u>

1. Project TETRIS. *雨伞设计*. <u>[PDF](TRIZ-related/TRIZ-ExamplesEN/EN_ex_2.pdf)</u>

1. Project TETRIS. *发动机创新连杆*. <u>[PDF](TRIZ-related/TRIZ-ExamplesEN/EN_ex_3.pdf)</u>

1. Project TETRIS. *防漏圆珠笔*. <u>[PDF](TRIZ-related/TRIZ-ExamplesEN/EN_ex_4.pdf)</u>

1. Project TETRIS. *清除冰冻输电线路上的冰*. <u>[PDF](TRIZ-related/TRIZ-ExamplesEN/EN_ex_5.pdf)</u>

来自 Oxford Creativity

6. Oxford Creativity. *40个发明原理及示例*.  <u>[PDF](TRIZ-related/TRIZ_40_inventive_principles_with_examplesfeb15.pdf)</u>

## Project TETRIS 文档

这些来自早期在意大利向学童教授 TRIZ 的项目。

1. Project TETRIS. *目录*. <u>[PDF](TRIZ-related/Project Tetris/cover_index_EN.pdf)</u>

2. Project TETRIS. *经典 TRIZ 基础*. <u>[PDF](TRIZ-related/Project Tetris/EN_01.pdf)</u>

3. Project TETRIS. *工程系统演化定律*. <u>[PDF](TRIZ-related/Project Tetris/EN_02.pdf)</u>

4. Project TETRIS. *Altshuller 发明问题解决算法 (ARIZ) 简短回顾图解*. <u>[PDF](TRIZ-related/Project Tetris/EN_03.pdf)</u>

5. Project TETRIS. *物-场分析和标准解*. <u>[PDF](TRIZ-related/Project Tetris/EN_04.pdf)</u>

6. Project TETRIS. *解决矛盾的技术 / 资源 / 效应*. <u>[PDF](TRIZ-related/Project Tetris/EN_05.pdf)</u>

## TRIZ 概念和方法

### 矛盾

1. Roni Horowitz 的 TRIZ40 网站。 <u>[[*映射到矛盾的发明原理详细列表!*](https://www.triz40.com/aff_Principles_TRIZ.php)</u>
优秀的可搜索矛盾数据库,带有示例。

1. Oxford TRIZ 矛盾矩阵。 <u>[PDF](TRIZ-related/oxfordtriz_contradictions_matrix.pdf)</u>

2. TRIZ Power Tools. *TRIZ 矛盾练习*. <u>[PDF](TRIZ-related/TRIZ_01_Contradictions_Exercises_Actual.pdf)</u>

1. Valeri Souchkov. *TRIZ 定义矛盾教程*. <u>[PDF](TRIZ-related/TRIZ_DefineContradiction_Tutorial.pdf)</u>


### 理想最终结果 (IFR)
1.

### 根本原因分析 + TRIZ

1. Karen Gadd. *TRIZ - 对任何使用根本原因分析 (RCA) 工具包的人都必不可少*. <u>[PDF](TRIZ-related/TRIZ and Root Cause Analysis Article by Karen Gadd.pdf)</u>

1. Oleg Abramov.(2015).*基于 TRIZ 的因果链分析 vs 根本原因分析*. TRIZfest 2015。 <u>[PDF](TRIZ-related/Abramov_TRIZfest-2015Paper_CECAvsRCA_final_published.pdf)</u>

### 发明原理:解释和示例

1. 40个发明原理图解。 <u>[PDF](TRIZ-related/40_principles_of_TRIZ_method_720dpi.jpg)</u>

2. TRIZ 发明原理及示例。 <u>[PDF](TRIZ-related/TRIZ_40_inventive_principles_with_examplesfeb15.pdf)</u>

3. TRIZ 发明原理单页参考。 <u>[PNG 图像](TRIZ-related/Triz IPs.png)</u>


## 高级 TRIZ 方法

1. 发明问题解决算法 (ARIZ)。 <u>[PDF](TRIZ-related/ariz85c_en.pdf)</u>. 这是 TRIZ 的高级版本。

2. Project TETRIS. *Altshuller 发明问题解决算法 (ARIZ) 简短回顾图解*. <u>[PDF](TRIZ-related/Project Tetris/EN_03.pdf)</u>

### TRIZ 中的物-场分析和科学效应

1. John Terninko, Ellen Domb, Joe Miller. *76个标准解及示例*. <u>[PDF](TRIZ-related/The 76 solutions.PDF)</u>


1. Davide Russo, Stefano Duci. (世界会议: TRIZ FUTURE, TF 2011-2014). *从 Altshuller 的76个标准解到新的111个标准解*. <u>[PDF](TRIZ-related/Altshuller 76 to 111 Inventive Solutions.pdf)</u>

1. Vladimir Petrov. *物-场度增加定律*. <u>[PDF](TRIZ-related/Petrov V. - The Law of Increasing Degree of Su-Field.pdf)</u>

1. Project TETRIS. *物-场分析和标准解*. <u>[PDF](TRIZ-related/Project Tetris/EN_04.pdf)</u>

## TRIZ 分离原理(用于物理矛盾)

1. TRIZ Power Tools. *TRIZ 分离原理,可视化*. <u>[PDF](TRIZ-related/TRIZ_08__Contradictions--Wall_Charts_Actual.pdf)</u>. 展示物理矛盾分离原理的图片。


### 系统-子系统-超系统
###


## TRIZ 案例研究

1. Chao, J. 和 Peng, C. (2016) *通过 TRIZ 分析实现雨伞高效太阳能*. 能源与动力工程, 8, 51-61. doi: <10.4236/epe.2016.82005>. <u>[PDF](TRIZ-related/Chao-etal-Solar-Electricity-Umbrella-Design.pdf.pdf)</u>

1. 科幻小说中的 TRIZ 矛盾。 <u>[PDF](TRIZ-related/Contradictions in Science Fiction.pdf)</u>

2. TRIZ 游戏。 <u>[PDF](TRIZ-related/PRIZM Game for TRIZ - Pahl.pdf)</u>

3. Oxford Creativity. *TRIZ 案例研究: Mars 巧克力包装*. <u>[PDF](TRIZ-related/TRIZ_case_study_-_pouch_opening_at_mars.pdf)</u>

## TRIZ 历史

1. KURYAN Andrei, KUCHARAVY Dmitry. (圣彼得堡, 2018年6月). *Nikolai N. KHOMENKO (TRIZ 大师 #59) 的 OTSM-TRIZ 遗产*. <u>[PDF](TRIZ-related/Khomenko_Heritage(EN).pdf)</u>

2. Darrell Mann, Simon Dewulf. *更新矛盾矩阵*. <u>[PDF](TRIZ-related/Updating_the_Contradiction_Matrix.pdf)</u>. 本文描述了 TRIZ 如何从矛盾矩阵中的39个参数发展到49个参数。


## TRIZ 期刊论文

1. Julian F. V. Vincent 和 Darrell L. Mann. (2002年2月15日)。 *系统技术从生物学到工程的转移*.
哲学学报:数学、物理和工程科学, 第360卷, 第1791期, 仿生学:从生物学到工程的技术转移, 第159-173页。 皇家学会。 <http://www.jstor.org/stable/3066299>. <u>[PDF](TRIZ-relatedD Mann - Succesful Technology transfer from Bio to Engg.pdf )</u>. Darrell Mann 的所有作品都值得阅读。

1. Julian F. V. Vincent, Olga A. Bogatyreva, Nikolaj R. Bogatyrev, Adrian Bowyer 和 Anja-Karina Pahl. *仿生学:其理论与实践*. <u>[PDF](TRIZ-related/Vincent-Biomimetics.pdf)</u>

1. Shiv Kumar, P. S. Bajwa, Kulbhushan. (2018年1月)。 *通过 TRIZ 解决问题的最新趋势:综述*. 创新科学与工程技术研究国际期刊。 第7卷, 第1期, 2018年1月。 <u>[PDF](TRIZ-related/24_IJIRSET_TRIZ.pdf)</u>

1. Denis Cavallucci. (2009年11月6日)。 *TRIZ 认知和使用的全球状况:调查结果*. TRIZFuture 2009, 蒂米什瓦拉, 罗马尼亚。 <u>[PDF](TRIZ-related/Cavallucci-TRIZ_survey_V2.pdf)</u>

1. 欧洲TRIZ协会期刊 INNOVATOR。 *特刊:
第14届国际 TRIZ 未来会议——全球创新大会发表的论文 - 洛桑/CERN, 2014年10月29-31日*。  <u>[PDF](TRIZ-related/ETRIAjournal2014vol01.pdf)</u>

1. Jennifer Harlim, Iouri Belski (2015)。 *论 TRIZ 工具发现问题有效性*.
工程论文集, 2015年12月。 DOI: 10.1016/j.proeng.2015.12.400.
<u>[PDF](TRIZ-related/HarlimTRIZProblemFindingProcedEng2015.pdf)</u>

1. Gunther Schuh, Christoph Haag. *如何使用新的基于 TRIZ 的方法论防止产品盗版*. TRIZ 未来会议2008, 发表于工程论文集(2011) 391–401。 <u>[PDF](TRIZ-related/How_to_prevent_product_piracy_using_a_new_TRIZ-bas.pdf)</u>

1. B. Cerit, G. Küçükyazıcı, 和 D. Şener.(2014) *TRIZ:发明问题解决理论及 TRIZ 与其他问题解决技术的比较*. 巴尔干电气与计算机工程期刊, 2014年, 第2卷, 第2期。 <u>[PDF](TRIZ-related/Comparison of TRIZ with the other Problem Solving Techniques.pdf)</u>

1. Prabhdeep Singh Bajwa, Dalgobind Mahto. (2013) *通过 TRIZ 解决问题的概念、工具和技术:综述*。
<u>[PDF](TRIZ-related/65_CONCEPTS.pdf)</u>

## 教授 TRIZ

1. Project TETRIS – 在学校教授 TRIZ。 <u><https://innovazionesistematica.it/en/project/tetris/></u>

1. Sergey Malkin, Donald Coates,Galina Malkin. *改进向学生教授发明问题解决理论的方法*. <u>[PDF](TRIZ-related/Malkin-Coates-an-improved-method-for-teaching-the-theory-of-inventive-problem-solving-to-students.pdf)</u>

1. Marianne W. Lewis, Gordon E. Dehler. *通过悖论学习:探索矛盾和复杂性的教学策略*. <u>[PDF](TRIZ-related/LewisDehlerJMEparadox2000.pdf)</u>

1. Wessel W. Wits,Tom H.J. Vaneker, Valeri Souchkov. *教育中的完全沉浸式 TRIZ*. <u>[PDF](TRIZ-related/WitsWessel - Full immersion TRIZ education.pdf)</u>

1. B. Cerit, G. Küçükyazıcı, 和 D. Şener. *TRIZ:发明问题解决理论及 TRIZ 与其他问题解决技术的比较*. 巴尔干电气与计算机工程期刊, 2014年, 第2卷, 第2期。 <u>[PDF](TRIZ-related/Comparison of TRIZ with the other Problem Solving Techniques.pdf)</u>


## TRIZ 相关网站

1. The TRIZ Journal. <u><https://the-trizjournal.com></u>

1. The TRIZ Journal 档案。 <u><https://www.metodolog.ru/triz-journal/></u>


1. Project TETRIS – 在学校教授 TRIZ。 <u><https://innovazionesistematica.it/en/project/tetris/></u>

1. 系统创新国际期刊(TRIZ 创新部分)。 <u><https://www.ijosi.org/index.php/IJOSI/catalog/category/2.1></u>

1. 创新科学与工程技术研究国际期刊。 <u><https://www.ijirset.com></u>

1. <u><https://online.eastt.ru></u>

1. <u><https://www.trizland.ru></u>

1. <u><https://www.altshuller.ru/world/eng/index.asp></u>

1. 欧洲TRIZ协会。 (ETRIA)。 <u><https://etria.eu/portal/></u>

1. MATRIZ 协会。 <u><https://matriz.org></u>

1. Nikolai Khomenko 的 OTSM-TRIZ。 <u><https://otsm-triz.org/en></u>

1. <u><https://www.thinking-approach.org/projecct/otsm-triz></u>

1. OTSM-TRIZ 技术中心: Jonathan Livingston 项目。 <u><http://www.trizminsk.org/eng/index.htm></u>

### 其他网站

1. 印度知识产权:可搜索专利数据库。<u><https://iprsearch.ipindia.gov.in/publicsearch></u>


### TRIZ 硕士和博士论文。
这些论文特别适合介绍章节中许多问题解决技术的概述。


1. Roni Horowitz.(1999年5月)。 博士论文, 特拉维夫大学。[*工程设计中的创造性问题解决*](https://asit.info/Creative%20Problem%20Solving%20in%20Engineering%20Design,%20thesis%20by%20Roni%20Horowitz.pdf).
非常易读。介绍章节尤其非常好。他在博士论文中从 TRIZ 推导出了 **ASIT** 技术。这里有一些很棒的 TRIZ 示例,这些示例作为我的 <u>[TRIZ 数据库](/slides/PlayAndInvent/TRIZ-Database/index.html)</u> 的一部分进行了分析。


1. Chhabin Pokhrel. *TRIZ 方法在过程工程问题解决中的适应性*。
拉彭兰塔理工大学, 技术学院。 <u>[PDF](TRIZ-related/Adaptation of TRIZ Method for Problem Solving in Process Engineering by Pokhrel Chhabin.pdf)</u>





