---
title: "TRIZ - At the Movies"
date: "2024-02-14"
date-modified: "`r Sys.Date()`"
order: 95
categories:
- Contradictions
- Reel World Problems
- TRIZ Inventive Principles

---

```{r}
#| label: setup
#| echo: false
#| 
```

## Introduction
To recap: 

We have seen:\

- How to examine an Object or a Situation 
- Use the Ishikawa Diagram to find Knobs and Settings
- Find one or more Administrative Contradictions(AC)  
- State the Ideal Final Result(IFR) to focus our attention  
- Convert the AC into a TC with 39 TRIZ Parameters  
- (Convert the AC into a PC)  
- Read the  TRIZ Inventive Principles(IPs) from the Contradiction Matrix
- Apply the TRIZ Inventive Principles to solve the Problem.

Here are a few iconic movies that we may consider as embodying very significant use of TRIZ Principles!! But here is a [***very very*** Administrative Contradiction for you to consider]{style="background-color:yellow;"}:

>We watch the movie and have fun, but we then have a monster of an Assignment to follow. 

Your call!!

## TRIZ at the Movies

Home Alone\
{{< youtube -6ZaHJkqwsI >}}<br>

Lawrence of Arabia\
{{< youtube xc0LIqZVhM8 >}} <br>

Castaway:\
{{< youtube 5qFJDndN9GQ >}} <br>

Apollo 13:\
{{< youtube 7RJnMME0XAw >}} <br>


## References

1. <https://www.cliohistory.org/thomas-lawrence/akaba>
1. Script from Lawrence of Arabia. <https://assets.scriptslug.com/live/pdf/scripts/lawrence-of-arabia-1962.pdf>
2. Filmsite.org: [Review of Lawrence of Arabia.](https://www.filmsite.org/lawr.html)
3. <https://sheldonkirshner.com/lawrence-of-arabia-the-movie-revisited>
4. <https://www.reddit.com/r/TrueFilm/comments/r7r7o4/lawrence_of_arabia_why_everyone_needs_to_watch_it/>

## More Readings

1. <https://medium.com/@arvind.venkatadri>

::: {.hidden .unlisted .unnumbered}

## Links {.hidden .unlisted .unnumbered}

1. <u><https://youtu.be/4hbru1nLBeU></u>

2. <u><https://youtu.be/nBiZu5C6lCo></u>

3. <u><https://youtu.be/Lu1ojHsMRrY></u>

4. <u><https://youtu.be/7RJnMME0XAw?si=ak5Tl7BWnNxbuLTI></u>

:::

