---
title: "TRIZ Problems Database"
date: 2025-Dec-07
date-modified: "`r Sys.Date()`"
---

```{r}
#| label: setup
```

## Introduction

This is a set of Problems that I am collecting from various TRIZ textbooks, websites, social media posts and other such places. 

At some point I will post analyses and solutions to some "preferred" ones and include these in my [Case Studies](../../../projects/listing.qmd).

## Problems

1. Problem 1. (Salamatov) A robot was brought to a plant to operate a machine. After it was rigged up
and switched on, the elderly worker who had operated the machine for years was
amazed at seeing the nimble ‘iron man’ performing all the necessary steps.
A half an hour later, however, the robot came to a standstill, to the bewilderment
of the service team of electronic engineers. What happened? As it turned out, some
chips had fallen from the workpiece into the moving element of the machine. This
situation where a human worker would simply flip the chips away with a broom and
continue working brought a robot to a deadlock. The engineers cleaned the machine
with a broom, switched on the robot... only to see the robot stop again. How could this
problem be solved? Obviously, one cannot attach a human worker with a broom to the
robot...

1. Problem 2. (Salamatov) A production line with robots installed at a clothing mill was unable to
perform the cutting and stitching of the pieces of clothes properly. The pieces of fabric
are not stiff, so the robots creased them with their grippers, stitched them Z-fold and
made many other slips. Using clamps and servo-systems equipped with optical sensors
and cameras did not help. Then it was suggested to wet the fabric so that it could stick firmly to the conveyer. And this, in turn, was useless, because the pieces were sticking
together, crumpled up and got deformed. What could be done?

1. Problem 3. (Salamatov) A wafer with IC and other electronic components is usually given a coat of
varnish that protects the wafer from exposure to negative interference. The varnish
coating is then dried under elevated temperature. At this stage microscopic bubbles of
gas evolve at some points of the wafer from the flux left after soldering, penetrating the
varnish coating before it dries up. The bubbles damage the integrity of the protective
coating. What can be done?

1. Problem 6. (Salamatov) While drilling deep boreholes in the earth it is essential to monitor the
condition of the teeth of the instrument that digs into the rock, for the teeth will break off
sometimes. Unaware of the condition of teeth, a technician has to work blindly, regularly
replacing the working instrument with a new one (just in case). To do this, the entire
column of pipes is pulled out of the borehole which is often a few miles deep. However,
replacing consumes too much time and labor. It is necessary to find a simple way to
control the condition of the working instrument.

1. Problem 7. (Salamatov) Everyone knows how the incubator works. But can incubation be carried
out in space? Space station provides all the necessary conditions for incubation
(atmosphere, heat), except one: gravity. That is why chickens simply won’t hatch! An
idea for the space incubator is wanted. What would you recommend for creating
artificial gravity?

1. Problem 8. (Salamatov) Edison used to offer ‘tricky’ technical problems to his would-be employees,
especially theoreticians. Once he invited a mathematician into his lab, and asked him to
calculate the volume of a bulb. For more than an hour the mathematician was busy
doing measurements and intricate calculations. He dealt with the task successfully and
proudly handed Edison a sheet of paper with the answer. To mathematician’s
bewilderment, in a few seconds Edison demonstrated an easier (and more reliable) way
to measure the bulb.

1. Problem 9. (Salamatov) The Dutch company advertises a device that provides rectilinear micro-
displacements (measuring hundredths of micrometers) in microscopes. The device is
very complex and contains an electric motor, a worm gear, a two-stage friction gear, all
components being made of special hard steel with exceptional, precision, accuracy.
The company emphasizes the advantages: no backlash, no lost motion, no lubricants
used.
Design a primitive device that uses a principle known from elementary school
physics, has no lost motion but greater accuracy.

1. ZEBRA OR WAVES? (Salamatov)
A town square was turned into a playground for children. At the same time it was impossible to
bar the traffic in an adjoining street. This gave rise to a problem: is it possible to make motorists
slow down while driving past the playground? Two proposals were put forth: covering a part of the
street with a zebra crossing or giving this section of the road a waved profile. The first way was
cheap but had a restricted effect, the second was safe but expensive. The desired solution should
combine the advantages but be devoid of the disadvantages. What would you suggest?

1. FIRE OR ABASEMENT? (Salamatov)
Lucas Cranach Junior, famous artist, was commissioned to paint a portrait of Cardinal Albrecht of
Brandenburg, a notoriously cruel figure of those days. Cardinal was to be depicted in his own
study, a Bible and a Crucifix in his hands. Showing the true character of Cardinal was out of
question, but compromising would be immoral. What could be done?
